name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_OAUTH_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build all
        run: yarn build

      - name: Creates release if necessary
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm whoami

          npm publish --access public